name = "cloudflareweb"
main = "worker.js"
compatibility_date = "2026-05-22"

[env.production]
name = "data-app-prod"
routes = [
  { pattern = "data-app.workers.dev", zone_name = "data-app.workers.dev" }
]

[[kv_namespaces]]
binding = "DATA_STORE"
id = "7b1355ff022442cba5a5cafe59bbdde7"

[observability]
enabled = true
